language: python
python:
- 2.7
install:
- pip install -r requirements-dev.txt
- pip install .
deploy:
  provider: pypi
  user: dbarroso
  password:
    secure: pITFguwG/dfyfJEVJZzB8W9L8ASLvAf5n6XzoKb5DtYBm12N4TmSBCHJNXYWMAPoyieeWeOzCOSfpZ3dqaIoLDZI/OJXL6ruGOi6O6kLCWa3TOu1JBCOtEW65PlPVce3nJyFh5Y/z384k2tGBVRTkQYlUkxMvsHaCAhIvf+iQqwrn7R5v28LazD5jZq8eH3JMnq9yY13hEveGevavgDChzaCMoxtXVQr4FW6gEXSEEpUBUhphBWqgom1faG0nZZbZPOWNZWcgCDFozQd2rz5vSqOBI44JpfZC1XGBJ8C/BKG44qoW1eMsE6uxrKVNP1YhvUHkLnYi3Hmodq5vBA+y8+MNr8IW3xwygYG3B4ciHaOb2HhLpGIyoF83GJHQ0kxKeRS35wRKGkr4QoCwCt3w5kw5epo2RFhhKA//Fjn4n8yg/aLlwqRpMWCsG817qLX4UwtLQmeL1xL0898C6gz2RhpzmmyNu7mhPunBsOoJff/PTmUXLQFlNXy1e7tmQK08gOrwKMpKLOJj8TWOPDZS7MaHeRUoTseXUoZYrswrcov7C1OdGOFvBt4x6Bi1PuhikOSoYXFyjNRrdW96VXDerIk+aCcTsgX37JYqTGOQXIy8sT21NqvwMWfC/mfyEzNWeKfPHXSIUV07wLL9F+9q11OyAbIed5AXARJ576X5ws=
  on:
    tags: true
    branch: master
script:
- pylama .
- cd test/unit
- cd ../..
